[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'preservim/nerdtree'

# [[plugins]] # markdown表示(不安定なので無効化してる)
# repo = 'skanehira/preview-markdown.vim'


[[plugins]] # Screen/Tmuxにコマンドを送る
repo = 'jpalardy/vim-slime'
[[plugins]] # ipython連携
repo = 'hanschen/vim-ipython-cell'


[[plugins]] # vim上でtermを立ててコマンドを送る
repo = 'williamjameshandley/vimteractive'


# [[plugins]] # python補完
# repo = 'davidhalter/jedi-vim'
# on_ft = 'python'

# [[plugins]] # 静的チェック
# repo = 'andviro/flake8-vim'

[[plugins]] # pep8インデント
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]] # vimでyamlのオートインデント
repo = 'chase/vim-ansible-yaml'

[[plugins]] # gcc/gcコメントアウト
repo = 'tpope/vim-commentary'

[[plugins]] # 自動で囲み終端生成
repo = 'jiangmiao/auto-pairs'

[[plugins]] # 範囲指定して囲み
repo = 'tpope/vim-surround'

[[plugins]] # indent表示
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # jinja2ハイライト
repo = 'Glench/Vim-Jinja2-Syntax'
